### PR TITLE
Attempt to fix inventory synchronization

### LINKED ISSUE #31: Client-Server inventory sync
Something wrong with visual updating backpack inventory on content changing.
As sample: Pick up stack of dirt from main inventory by lclick; put just 1 dirt to backpack by rclick; lclick 63 remaining units to same slot; backpack shows only one piece of dirt.
Or shift-click 1 dirt from main inventory to backpack; then shift-click some more (but less then 64); again shows only one piece of dirt. And so on.
Its only visual mess. After reopening backpack shows all stacks as intended.

### PR DESCRIPTION
**Pull request by Ugachaga**
To be honest, I have no idea why @Darkona disabled this code. It fixes https://github.com/runescapejon/AdventureBackpack2/issues/31 for me.

### CODE REVIEW

**Comment by runescapejon** [comment]
Thanks

**Comment by runescapejon** [comment]
okay i see why @Darkona disable that part of the code it's because another bug had re-created when you stack the item you will see that glitches going to fix this soon

**Comment by Ugachaga** [comment]
For you info: same code found in ContainerJetpack.java, it was enabled all the time.

**Comment by Ugachaga** [comment]
I think I understand why the code has been disabled. It causes big performance problems, it is noticeable on large modpacks like GT New Horizons. The proper use of this method would not be executed at each tick for each listener while backpack is open, but only if there have been changes and only for changed stacks. In the current state it must be disabled asap.

**Pull request merged**
