### PR TITLE
change GT biofuel to biodiesel

### PR DESCRIPTION
**Pull request by Dream-Master**
@Ugachaga @runescapejon BioFuel not have a use so far i can see. I guess Bio Diesel is a better option here.

### CODE REVIEW

**Comment by Ugachaga** [comment]
I think BioFuel is an MFR fluid. So it's better to keep them both for other modpacks. Also simple adding new type of fuel souldn't requere code change. I'll make PR.

**Comment by Ugachaga** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9g20

**Comment by Dream-Master** [comment]
Sure. I don't use mfr and see a question mark in code.

**Comment by Dream-Master** [comment]
But have both is nice too.

**Pull request closed without merging**
