### PR TITLE
Boat got name

### PR DESCRIPTION
**Pull request by Ugachaga**
Reorganized config, added categories and subcategories
Added options to precisely setting up position of Status Overlay, same for Backpack Overlay. This and most others options can be configured in the game "mod options"
Added configs: sound for Jetpack and PistonBoots, recipes for weapons and wearables
Added config for filtering allowed items by localized and unlocalized name or ID.
Added Bluepower, ProjectRed and ExtraUtilities bags to hardcoded disallowed items.
Added config for disable hose drinking mode.
Added key for switch tool cycling mode - BackpackToggleKey when wearing backpack.

Boat got name :P

NOTE: due to changed config file structure you have to reconfig mod. You may just delete previous adventurebackpack.cfg , it will recreated at the game start, then make your changes via "mod options" or to adventurebackpack.cfg directly

### CODE REVIEW

**Comment by Ugachaga** [comment]
Sample overlays:

**Comment by runescapejon** [comment]
Wow Thanks for working on the adventure backpack mod

**Comment by runescapejon** [comment]
If anyone using Bungeecord and not using Forcehost feature within Bungeecord then do not use this until the bug is fixed, this creates another bug and fully unable to play with the mod on a bungeecord server

**Comment by Ugachaga** [comment]
There's not many changes. If you tell me when new bug with Bungeecord appears and what exactly bug, so I can rewrite or disable that part of code. I bet it's not related to boat name xD

**Comment by runescapejon** [comment]
just read #20 and it's an weird bug

**Comment by Ugachaga** [comment]
Oh, you were talking about an old bug. I thought that I made a new one.
So if there is no new bugs, do you plan to release this version?

**Comment by runescapejon** [comment]
there a new bug it pretty much made it worse for bungeecord, if an server owner has bungeecord and don't use force host, they can't killed them self to see the backpack like it use too before you made this.

**Comment by Ugachaga** [comment]
Kill himself to see backpack ... sounds odd. As I understand it is impossible to play without force host anyway, so new bug make it harder for, say, tests. Well, I do not use Bungeecord, so only thing can be done is try to disable some changes from last PR.

**Comment by Eufranio** [comment]
I use and can test if you guys want...

**Comment by runescapejon** [comment]
nah it's fine i have an bungeecord i don't mind testing it with this bug i'm not sure it's Bungeecord at fault or us

**Comment by Ugachaga** [comment]
There is minor bug with geting fluid tanks status when you just connected to the game. Perhaps Bungeecord issue also due to improper initialization when connecting.

**Comment by runescapejon** [comment]
right but i don't think it's an issue with improper initialization connection cause i was using this https://github.com/HexagonMC/BungeeCord and they seem fine

**Comment by Ugachaga** [comment]
@runescapejon I mean it's backpacks issue.
@Eufranio You can test this version if you want, I posted pre-release [here](https://github.com/Ugachaga/AdventureBackpack2/releases)

**Comment by runescapejon** [comment]
hm you may be right about it

**Comment by Eufranio** [comment]
@Ugachaga still same issue about Bungee. The client doesn't detect that the player (me) is using a backpack, then we can't open it. I can see other's backpacks, tho.

**Pull request merged**
