### PR TITLE
Try to fixe some things

### PR DESCRIPTION
**Pull request by Dream-Master**
Try to fixe some things.

Not sure if i did all things right.

### CODE REVIEW

**Comment by Dream-Master** [comment]
Known Issue with this is that the Steam Tank is named as Water Tank.

image

**Comment by runescapejon** [comment]
Thanks but i don't see the point in adding git ignore if your doing the code right then your fine xD

**Comment by Dream-Master** [comment]
Oh  I forgot to Remove  Git ignore. Will you then add the code?

**Comment by runescapejon** [comment]
yea but it will take me sometime because i am reworking the while shift idea thing

**Comment by Dream-Master** [comment]
no problem take your time.

**Pull request closed without merging**
